# Generated by Django 5.1.1 on 2024-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name_plural": "children"},
        ),
        migrations.AlterField(
            model_name="parent",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="parent name"
            ),
        ),
    ]
